/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javafxmathml;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.web.HTMLEditor;
import javafx.scene.web.WebView;
import javafx.stage.Stage;
import org.w3c.dom.Document;

/**
 *
 * @author scientificware2015
 */
public class JavaFXMathML extends Application {

    @Override
    public void start(Stage primaryStage) {
        primaryStage.setTitle("Guy Abossolo Foh 5 mai 2016 - JavaFX et MathML");
        primaryStage.setWidth(400);
        primaryStage.setHeight(500);

        final myHTMLEditor htmlEditor = new myHTMLEditor();
        htmlEditor.setHtmlText(content);

        primaryStage.setScene(new Scene(htmlEditor));
        primaryStage.show();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        launch(args);
    }

    WebView webview = new WebView();

    String javaversion = "Version de Java.. : " + System.getProperty("java.runtime.version");
    String javafxversion = "Version de JavaFX : " + System.getProperty("javafx.runtime.version");
    String osinfo = "OS .............. : " + System.getProperty("os.name");
    String osarch = "CPU ............. : " + System.getProperty("os.arch");
    String agent = "User Agent ...... : " + webview.getEngine().getUserAgent();

    String Content2 = "<table>"
            + "<tr>"
            + "<td></td>"
            + "<th scope=\"col\">As rendered by TeX</th>"
            + "<th scope=\"col\">As rendered by your browser</th></tr>"
            + "<tr>"
            + "<td>1</td>"
            + "<td><img src=\"https://developer.mozilla.org/@api/deki/files/4578/=ex1.png\" width=\"38\" height=\"22\""
            + "alt=\"TeXbook, 16.2-16.3\" /></td>"
            + "<td>"
            + "<math display=\"block\">"
            + "<mrow>"
            + "  <msup>"
            + "    <mi>x</mi>"
            + "    <mn>2</mn>"
            + "  </msup>"
            + "  <msup>"
            + "    <mi>y</mi>"
            + "    <mn>2</mn>"
            + "  </msup>"
            + "</mrow>"
            + "</math>"
            + "</td></tr>"
            + "<tr>"
            + "<td>2</td>"
            + "<td><img src=\"https://developer.mozilla.org/@api/deki/files/4579/=ex2.png\" width=\"30\" height=\"17\" alt=\"TeXbook, 16.2-16.3\" /></td>"
            + "<td>"
            + "<math display=\"block\">"
            + "<!--"
            + "<mrow>"
            + "  <msub><mi></mi><mn>2</mn></msub>"
            + "  <msub><mi>F</mi><mn>3</mn></msub>"
            + "</mrow>"
            + "-->"
            + "<mrow>"
            + "  <mmultiscripts>"
            + "    <mi>F</mi>"
            + "    <mn>3</mn><none/>"
            + "    <mprescripts/>"
            + "    <mn>2</mn><none/>"
            + "  </mmultiscripts>"
            + "</mrow>"
            + "</math>"
            + "</td></tr>"
            + "<tr>"
            + "<td>3</td>"
            + "<td><img src=\"https://developer.mozilla.org/@api/deki/files/4586/=ex21.png\" width=\"58\" height=\"47\" alt=\"TeXbook, 17-17.1\" /></td>"
            + "<td>"
            + "<math display=\"block\">"
            + "<mrow>"
            + "  <mfrac>"
            + "    <mrow>"
            + "      <mi>x</mi>"
            + "      <mo>+</mo>"
            + "      <msup>"
            + "        <mi>y</mi>"
            + "        <mn>2</mn>"
            + "      </msup>"
            + "    </mrow>"
            + "    <mrow>"
            + "      <mi>k</mi>"
            + "      <mo>+</mo>"
            + "      <mn>1</mn>"
            + "    </mrow>"
            + "  </mfrac>"
            + "</mrow>"
            + "</math>"
            + "</td></tr>"
            + "<tr>"
            + "<td>4</td>"
            + "<td><img src=\"https://developer.mozilla.org/@api/deki/files/4587/=ex22.png\" width=\"76\" height=\"25\" alt=\"TeXbook, 17-17.1\" /></td>"
            + "<td>"
            + "<math display=\"block\">"
            + "<mrow>"
            + "  <mi>x</mi>"
            + "  <mo>+</mo>"
            + "  <msup>"
            + "    <mi>y</mi>"
            + "    <mfrac>"
            + "      <mn>2</mn>"
            + "      <mrow>"
            + "        <mi>k</mi>"
            + "        <mo>+</mo>"
            + "        <mn>1</mn>"
            + "      </mrow>"
            + "    </mfrac>"
            + "  </msup>"
            + "</mrow>"
            + "</math>"
            + "</td></tr>"
            + "<tr>"
            + "<td>5</td>"
            + "<td><img src=\"https://developer.mozilla.org/@api/deki/files/4588/=ex23.png\" width=\"30\" height=\"42\" alt=\"TeXbook, 17-17.1\" /></td>"
            + "<td>"
            + "<math display=\"block\">"
            + "<mrow>"
            + "  <mfrac>"
            + "    <mi>a</mi>"
            + "    <mrow>"
            + "      <mi>b</mi>"
            + "      <mo>/</mo>"
            + "      <mn>2</mn>"
            + "    </mrow>"
            + "  </mfrac>"
            + "</mrow>"
            + "</math>"
            + "</td></tr>"
            + "<tr>"
            + "<td>6</td>"
            + "<td><img src=\"https://developer.mozilla.org/@api/deki/files/4589/=ex24.png\" width=\"220\" height=\"138\" alt=\"TeXbook, 17.5-17.6\" /></td>"
            + "<td>"
            + "<math display=\"block\">"
            + "<mrow>"
            + "  <msub>"
            + "    <mi>a</mi>"
            + "    <mn>0</mn>"
            + "  </msub>"
            + "  <mo>+</mo>"
            + "  <mfrac>"
            + "    <mn>1</mn>"
            + "    <mstyle displaystyle=\"true\" scriptlevel=\"0\">"
            + "      <msub>"
            + "        <mi>a</mi>"
            + "        <mn>1</mn>"
            + "      </msub>"
            + "      <mo>+</mo>"
            + "      <mfrac>"
            + "        <mn>1</mn>"
            + "        <mstyle displaystyle=\"true\" scriptlevel=\"0\">"
            + "          <msub>"
            + "            <mi>a</mi>"
            + "            <mn>2</mn>"
            + "          </msub>"
            + "          <mo>+</mo>"
            + "          <mfrac>"
            + "            <mn>1</mn>"
            + "            <mstyle displaystyle=\"true\" scriptlevel=\"0\">"
            + "              <msub>"
            + "                <mi>a</mi>"
            + "                <mn>3</mn>"
            + "              </msub>"
            + "              <mo>+</mo>"
            + "              <mfrac>"
            + "                <mn>1</mn>"
            + "                <mstyle displaystyle=\"true\" scriptlevel=\"0\">"
            + "                  <msub>"
            + "                    <mi>a</mi>"
            + "                    <mn>4</mn>"
            + "                  </msub>"
            + "                </mstyle>"
            + "              </mfrac>"
            + "            </mstyle>"
            + "          </mfrac>"
            + "        </mstyle>"
            + "      </mfrac>"
            + "    </mstyle>"
            + "  </mfrac>"
            + "</mrow>"
            + "</math>"
            + "</td></tr>"
            + "<tr>"
            + "<td>7</td>"
            + "<td><img src=\"https://developer.mozilla.org/@api/deki/files/4590/=ex25.png\" width=\"200\" height=\"85\" alt=\"TeXbook, 17.5-17.6\" /></td>"
            + "<td>"
            + "<math>"
            + "<mrow>"
            + "  <msub>"
            + "    <mi>a</mi>"
            + "    <mn>0</mn>"
            + "  </msub>"
            + "  <mo>+</mo>"
            + "  <mfrac>"
            + "    <mn>1</mn>"
            + "    <mrow>"
            + "      <msub>"
            + "        <mi>a</mi>"
            + "        <mn>1</mn>"
            + "      </msub>"
            + "      <mo>+</mo>"
            + "      <mfrac>"
            + "        <mn>1</mn>"
            + "        <mrow>"
            + "          <msub>"
            + "            <mi>a</mi>"
            + "            <mn>2</mn>"
            + "          </msub>"
            + "          <mo>+</mo>"
            + "          <mfrac>"
            + "            <mn>1</mn>"
            + "            <mrow>"
            + "              <msub>"
            + "                <mi>a</mi>"
            + "                <mn>3</mn>"
            + "              </msub>"
            + "              <mo>+</mo>"
            + "              <mfrac>"
            + "                <mn>1</mn>"
            + "                <mrow>"
            + "                  <msub>"
            + "                    <mi>a</mi>"
            + "                    <mn>4</mn>"
            + "                  </msub>"
            + "                </mrow>"
            + "              </mfrac>"
            + "            </mrow>"
            + "          </mfrac>"
            + "        </mrow>"
            + "      </mfrac>"
            + "    </mrow>"
            + "  </mfrac>"
            + "</mrow>"
            + "</math>"
            + "</td></tr>"
            + "<tr>"
            + "<td>8</td>"
            + "<td><img src=\"https://developer.mozilla.org/@api/deki/files/4591/=ex26.png\" width=\"54\" height=\"50\" alt=\"TeXbook, 17.5-17.6\" /></td>"
            + "<td>"
            + "<math display=\"block\">"
            + "<mrow>"
            + "  <mo>(</mo>"
            + "  <mfrac linethickness=\"0\">"
            + "    <mi>n</mi>"
            + "    <mrow>"
            + "      <mi>k</mi>"
            + "      <mo>/</mo>"
            + "      <mn>2</mn>"
            + "    </mrow>"
            + "  </mfrac>"
            + "  <mo>)</mo>"
            + "</mrow>"
            + "</math>"
            + "</td></tr>"
            + "<tr>"
            + "<td>9</td>"
            + "<td><img src=\"https://developer.mozilla.org/@api/deki/files/4592/=ex27.png\" width=\"237\" height=\"50\" alt=\"TeXbook, 17.7\" /></td>"
            + "<td>"
            + "<math display=\"block\">"
            + "<mrow>"
            + "  <mrow>"
            + "    <mo>(</mo>"
            + "    <mfrac linethickness=\"0\">"
            + "      <mi>p</mi>"
            + "      <mn>2</mn>"
            + "    </mfrac>"
            + "    <mo>)</mo>"
            + "  </mrow>"
            + "  <msup>"
            + "    <mi>x</mi>"
            + "    <mn>2</mn>"
            + "  </msup>"
            + "  <msup>"
            + "    <mi>y</mi>"
            + "    <mrow>"
            + "      <mi>p</mi>"
            + "      <mo>-</mo>"
            + "      <mn>2</mn>"
            + "    </mrow>"
            + "  </msup>"
            + "  <mo>-</mo>"
            + "  <mfrac>"
            + "    <mn>1</mn>"
            + "    <mrow>"
            + "      <mn>1</mn>"
            + "      <mo>-</mo>"
            + "      <mi>x</mi>"
            + "    </mrow>"
            + "  </mfrac>"
            + "  <mfrac>"
            + "    <mn>1</mn>"
            + "    <mrow>"
            + "      <mn>1</mn>"
            + "      <mo>-</mo>"
            + "      <msup>"
            + "        <mi>x</mi>"
            + "        <mn>2</mn>"
            + "      </msup>"
            + "    </mrow>"
            + "  </mfrac>"
            + "</mrow>"
            + "</math>"
            + "</td></tr>"
            + "<tr>"
            + "<td>10</td>"
            + "<td><img src=\"https://developer.mozilla.org/@api/deki/files/4593/=ex29.png\" width=\"116\" height=\"63\" alt=\"TeXbook, 17.7-17.8\" /></td>"
            + "<td>"
            + "<math display=\"block\">"
            + "<mrow>"
            + "  <munder>"
            + "    <mo>&sum;</mo>"
            + "    <mrow>"
            + "      <mfrac linethickness=\"0\">"
            + "        <mrow>"
            + "          <mn>0</mn>"
            + "          <mo>&leq;</mo>"
            + "          <mi>i</mi>"
            + "          <mo>&leq;</mo>"
            + "          <mi>m</mi>"
            + "        </mrow>"
            + "        <mrow>"
            + "          <mn>0</mn>"
            + "          <mo>&lt;</mo>"
            + "          <mi>j</mi>"
            + "          <mo>&lt;</mo>"
            + "          <mi>n</mi>"
            + "        </mrow>"
            + "      </mfrac>"
            + "    </mrow>"
            + "  </munder>"
            + "  <mi>P</mi>"
            + "  <mo stretchy=\"false\">(</mo>"
            + "  <mi>i</mi>"
            + "  <mo>,</mo>"
            + "  <mi>j</mi>"
            + "  <mo stretchy=\"false\">)</mo>"
            + "</mrow>"
            + "</math>"
            + "</td></tr>"
            + "<tr>"
            + "<td>11</td>"
            + "<td><img src=\"https://developer.mozilla.org/@api/deki/files/4580/=ex3.png\" width=\"27\" height=\"18\" alt=\"TeXbook, 16.2-16.3\" /></td>"
            + "<td>"
            + "<math display=\"block\">"
            + "<mrow>"
            + "<msup>"
            + "  <mi>x</mi>"
            + "  <mrow>"
            + "    <mn>2</mn>"
            + "    <mi>y</mi>"
            + "  </mrow>"
            + "</msup>"
            + "</mrow>"
            + "</math>"
            + "</td></tr>"
            + "<tr>"
            + "<td>12</td>"
            + "<td><img src=\"https://developer.mozilla.org/@api/deki/files/4594/=ex30.png\" width=\"175\" height=\"61\" alt=\"TeXbook, 17.8\" /></td>"
            + "<td>"
            + "<math display=\"block\">"
            + "<mrow>"
            + "  <munderover>"
            + "    <mo>&sum;</mo>"
            + "    <mrow>"
            + "      <mi>i</mi>"
            + "      <mo>=</mo>"
            + "      <mn>1</mn>"
            + "    </mrow>"
            + "    <mi>p</mi>"
            + "  </munderover>"
            + "  <munderover>"
            + "    <mo>&sum;</mo>"
            + "    <mrow>"
            + "      <mi>j</mi>"
            + "      <mo>=</mo>"
            + "      <mn>1</mn>"
            + "    </mrow>"
            + "    <mi>q</mi>"
            + "  </munderover>"
            + "  <munderover>"
            + "    <mo>&sum;</mo>"
            + "    <mrow>"
            + "      <mi>k</mi>"
            + "      <mo>=</mo>"
            + "      <mn>1</mn>"
            + "    </mrow>"
            + "    <mi>r</mi>"
            + "  </munderover>"
            + "  <msub>"
            + "    <mi>a</mi>"
            + "    <mrow>"
            + "      <mi>i</mi>"
            + "      <mi>j</mi>"
            + "    </mrow>"
            + "  </msub>"
            + "  <msub>"
            + "    <mi>b</mi>"
            + "    <mrow>"
            + "      <mi>j</mi>"
            + "      <mi>k</mi>"
            + "    </mrow>"
            + "  </msub>"
            + "  <msub>"
            + "    <mi>c</mi>"
            + "    <mrow>"
            + "      <mi>k</mi>"
            + "      <mi>i</mi>"
            + "    </mrow>"
            + "  </msub>"
            + "</mrow>"
            + "</math>"
            + "</td></tr>"
            + "<tr>"
            + "<td>13</td>"
            + "<td><img src=\"https://developer.mozilla.org/@api/deki/files/4595/=ex31.png\" width=\"405\" height=\"100\" alt=\"TeXbook, 17.9-17.10\" /></td>"
            + "<td>"
            + "<math display=\"block\">"
            + "<mrow>"
            + "  <msqrt>"
            + "    <mn>1</mn>"
            + "    <mo>+</mo>"
            + "    <msqrt>"
            + "      <mn>1</mn>"
            + "      <mo>+</mo>"
            + "      <msqrt>"
            + "        <mn>1</mn>"
            + "        <mo>+</mo>"
            + "        <msqrt>"
            + "          <mn>1</mn>"
            + "          <mo>+</mo>"
            + "          <msqrt>"
            + "            <mn>1</mn>"
            + "            <mo>+</mo>"
            + "            <msqrt>"
            + "              <mn>1</mn>"
            + "              <mo>+</mo>"
            + "              <msqrt>"
            + "                <mn>1</mn>"
            + "                <mo>+</mo>"
            + "                <mi>x</mi>"
            + "              </msqrt>"
            + "            </msqrt>"
            + "          </msqrt>"
            + "        </msqrt>"
            + "      </msqrt>"
            + "    </msqrt>"
            + "  </msqrt>"
            + "</mrow>"
            + "</math>"
            + "</td></tr>"
            + "<tr>"
            + "<td>14</td>"
            + "<td><img src=\"https://developer.mozilla.org/@api/deki/files/4596/=ex34.png\" width=\"272\" height=\"50\" alt=\"TeXbook, 17.10\" /></td>"
            + "<td>"
            + "<math display=\"block\">"
            + "<mrow>"
            + "  <mrow>"
            + "    <mo>(</mo>"
            + "    <mfrac>"
            + "      <msup>"
            + "        <mo>&part;</mo>"
            + "        <mn>2</mn>"
            + "      </msup>"
            + "      <mrow>"
            + "        <mo>&part;</mo>"
            + "        <msup>"
            + "          <mi>x</mi>"
            + "          <mn>2</mn>"
            + "        </msup>"
            + "      </mrow>"
            + "    </mfrac>"
            + "    <mo>+</mo>"
            + "    <mfrac>"
            + "      <msup>"
            + "        <mo>&part;</mo>"
            + "        <mn>2</mn>"
            + "      </msup>"
            + "      <mrow>"
            + "        <mo>&part;</mo>"
            + "        <msup>"
            + "          <mi>y</mi>"
            + "          <mn>2</mn>"
            + "        </msup>"
            + "      </mrow>"
            + "    </mfrac>"
            + "    <mo>)</mo>"
            + "  </mrow>"
            + "  <msup>"
            + "    <mrow>"
            + "      <mo minsize=\"1.5\">|</mo>"
            + "      <mi>&#x3C6; <!-- \\varphi --></mi>"
            + "      <mo stretchy=\"false\">(</mo>"
            + "      <mi>x</mi>"
            + "      <mo>+</mo>"
            + "      <mi mathvariant=\"normal\">i</mi>"
            + "      <mi>y</mi>"
            + "      <mo stretchy=\"false\">)</mo>"
            + "      <mo minsize=\"1.5\">|</mo>"
            + "    </mrow>"
            + "    <mn>2</mn>"
            + "  </msup>"
            + "  <mo>=</mo>"
            + "  <mn>0</mn>"
            + "</mrow>"
            + "</math>"
            + "</td></tr>"
            + "<tr>"
            + "<td>15</td>"
            + "<td><img src=\"https://developer.mozilla.org/@api/deki/files/4581/=ex4.png\" width=\"31\" height=\"22\" alt=\"TeXbook, 16.2-16.3\" /></td>"
            + "<td>"
            + "<math display=\"block\">"
            + "<mrow>"
            + "  <msup>"
            + "    <mn>2</mn>"
            + "    <msup>"
            + "      <mn>2</mn>"
            + "      <msup>"
            + "        <mn>2</mn>"
            + "        <mi>x</mi>"
            + "      </msup>"
            + "    </msup>"
            + "  </msup>"
            + "</mrow>"
            + "</math>"
            + "</td></tr>"
            + "<tr>"
            + "<td>16</td>"
            + "<td><img src=\"https://developer.mozilla.org/@api/deki/files/4597/=ex40.png\" width=\"55\" height=\"49\" alt=\"TeXbook, 18.10-18.11\" /></td>"
            + "<td>"
            + "<math display=\"block\">"
            + "<mrow>"
            + "  <msubsup>"
            + "    <mo stretchy=\"false\">&int;</mo>"
            + "    <mn>1</mn>"
            + "    <mi>x</mi>"
            + " </msubsup>"
            + " <mfrac>"
            + "   <mrow><mi>d</mi><mi>t</mi></mrow>"
            + "   <mi>t</mi>"
            + " </mfrac>"
            + "</mrow>"
            + "</math>"
            + "</td></tr>"
            + "<tr>"
            + "<td>17</td>"
            + "<td><img src=\"https://developer.mozilla.org/@api/deki/files/4599/=ex41.png\" width=\"91\" height=\"47\" alt=\"TeXbook, 18.12-18.13\" /></td>"
            + "<td>"
            + "<math display=\"block\">"
            + "<mrow>"
            + "  <msub>"
            + "    <mo>&#x222C; <!-- \\iint --></mo>"
            + "    <mi>D</mi>"
            + "  </msub>"
            + "  <mi>d</mi><mi>x</mi>"
            + "  <space width=\"thinmathspace\"/>"
            + "  <mi>d</mi><mi>y</mi>"
            + "</mrow>"
            + "</math>"
            + "</td></tr>"
            + "<tr>"
            + "<td>18</td>"
            + "<td><img src=\"https://developer.mozilla.org/@api/deki/files/4600/=ex43.png\" width=\"250\" height=\"66\" alt=\"TeXbook, 18.23\" /></td>"
            + "<td>"
            + "<math display=\"block\">"
            + "<mrow>"
            + "  <mi>f</mi>"
            + "  <mo stretchy=\"false\">(</mo>"
            + "  <mi>x</mi>"
            + "  <mo stretchy=\"false\">)</mo>"
            + "  <mo>=</mo>"
            + "  <mrow>"
            + "    <mo>{</mo>"
            + "    <mtable>"
            + "      <mtr>"
            + "        <mtd columnalign=\"center\">"
            + "          <mrow>"
            + "            <mn>1</mn>"
            + "            <mo>/</mo>"
            + "            <mn>3</mn>"
            + "          </mrow>"
            + "        </mtd>"
            + "        <mtd columnalign=\"left\">"
            + "          <mrow>"
            + "            <mtext>if </mtext>"
            + "            <mn>0</mn>"
            + "            <mo>&leq;</mo>"
            + "            <mi>x</mi>"
            + "            <mo>&leq;</mo>"
            + "            <mn>1</mn>"
            + "            <mo>;</mo>"
            + "          </mrow>"
            + "        </mtd>"
            + "      </mtr>"
            + "      <mtr>"
            + "        <mtd columnalign=\"center\">"
            + "          <mrow>"
            + "            <mn>2</mn>"
            + "            <mo>/</mo>"
            + "            <mn>3</mn>"
            + "          </mrow>"
            + "        </mtd>"
            + "        <mtd columnalign=\"center\">"
            + "          <mrow>"
            + "            <mtext>if </mtext>"
            + "            <mn>3</mn>"
            + "            <mo>&leq;</mo>"
            + "            <mi>x</mi>"
            + "            <mo>&leq;</mo>"
            + "            <mn>4</mn>"
            + "            <mo>;</mo>"
            + "          </mrow>"
            + "        </mtd>"
            + "      </mtr>"
            + "      <mtr>"
            + "        <mtd columnalign=\"center\">"
            + "          <mn>0</mn>"
            + "        </mtd>"
            + "        <mtd columnalign=\"left\">"
            + "          <mtext>elsewhere.</mtext>"
            + "        </mtd>"
            + "      </mtr>"
            + "    </mtable>"
            + "  </mrow>"
            + "</mrow>"
            + "</math>"
            + "</td></tr>"
            + "<tr>"
            + "<td>19</td>"
            + "<td><img src=\"https://developer.mozilla.org/@api/deki/files/4601/=ex44.png\" width=\"101\" height=\"44\" alt=\"TeXbook, 18.23-18.24\" /></td>"
            + "<td>"
            + "<math display=\"block\">"
            + "<mover>"
            + "  <mrow>"
            + "    <mi>x</mi>"
            + "    <mo>+</mo>"
            + "    <mo>...</mo>"
            + "    <mo>+</mo>"
            + "    <mi>x</mi>"
            + "  </mrow>"
            + "  <mover>"
            + "    <mo>&OverBrace;</mo>"
            + "    <mrow><mi>k</mi> <mspace width=\"thinmathspace\"/> <mtext>times</mtext></mrow>"
            + "  </mover>"
            + "</mover>"
            + "</math>"
            + "</td></tr>"
            + "<tr>"
            + "<td>20</td>"
            + "<td><img src=\"https://developer.mozilla.org/@api/deki/files/4582/=ex5.png\" width=\"25\" height=\"13\" alt=\"TeXbook, 16.2-16.3\" /></td>"
            + "<td>"
            + "<math display=\"block\">"
            + "<mrow>"
            + "  <msub>"
            + "    <mi>y</mi>"
            + "    <msup>"
            + "      <mi>x</mi>"
            + "      <mn>2</mn>"
            + "    </msup>"
            + "  </msub>"
            + "</mrow>"
            + "</math>"
            + "</td></tr>"
            + "<tr>"
            + "<td>21</td>"
            + "<td><img src=\"https://developer.mozilla.org/@api/deki/files/4602/=ex51.png\" width=\"253\" height=\"56\" alt=\"TeXbook, 18.40\" /></td>"
            + "<td>"
            + "<math display=\"block\">"
            + "<mrow>"
            + "  <munder>"
            + "    <mo>&sum;</mo>"
            + "    <mrow>"
            + "      <mi>p</mi>"
            + "      <mtext> prime</mtext>"
            + "    </mrow>"
            + "  </munder>"
            + "  <mi>f</mi>"
            + "  <mo stretchy=\"false\">(</mo>"
            + "  <mi>p</mi>"
            + "  <mo stretchy=\"false\">)</mo>"
            + "  <mo>=</mo>"
            + "  <msub>"
            + "    <mo stretchy=\"false\">&int;</mo>"
            + "    <mrow>"
            + "      <mi>t</mi>"
            + "      <mo>&gt;</mo>"
            + "      <mn>1</mn>"
            + "    </mrow>"
            + "  </msub>"
            + "  <mi>f</mi>"
            + "  <mo stretchy=\"false\">(</mo>"
            + "  <mi>t</mi>"
            + "  <mo stretchy=\"false\">)</mo>"
            + "  <mspace width=\"thinmathspace\"/>"
            + "  <mi>d</mi>"
            + "  <mi>&pi;</mi>"
            + "  <mo stretchy=\"false\">(</mo>"
            + "  <mi>t</mi>"
            + "  <mo stretchy=\"false\">)</mo>"
            + "</mrow>"
            + "</math>"
            + "</td></tr>"
            + "<tr>"
            + "<td>22</td>"
            + "<td><img src=\"https://developer.mozilla.org/@api/deki/files/4603/=ex52.png\" width=\"159\" height=\"81\" alt=\"TeXbook, 18.41\" /></td>"
            + "<td>"
            + "<math display=\"block\">"
            + "<mrow>"
            + "  <mo stretchy=\"false\">{</mo>"
            + "  <munder>"
            + "    <mrow>"
            + "      <mover>"
            + "        <mrow>"
            + "          <mpadded width=\"0em\"><mphantom><mo>(</mo></mphantom></mpadded>"
            + "          <mi>a</mi>"
            + "          <mo>,</mo>"
            + "          <mo>...</mo>"
            + "          <mo>,</mo>"
            + "          <mi>a</mi>"
            + "        </mrow>"
            + "        <mover>"
            + "          <mo>&OverBrace;</mo>"
            + "          <mrow>"
            + "            <mi>k</mi>"
            + "            <mtext> </mtext>"
            + "            <mi>a</mi>"
            + "            <mtext>'s</mtext>"
            + "          </mrow>"
            + "        </mover>"
            + "      </mover>"
            + "      <mo>,</mo>"
            + "      <mover>"
            + "        <mrow>"
            + "          <mpadded width=\"0em\"><mphantom><mo>(</mo></mphantom></mpadded>"
            + "          <mi>b</mi>"
            + "          <mo>,</mo>"
            + "          <mo>...</mo>"
            + "          <mo>,</mo>"
            + "          <mi>b</mi>"
            + "        </mrow>"
            + "        <mover>"
            + "          <mo>&OverBrace;</mo>"
            + "          <mrow>"
            + "            <mi>&ell;</mi>"
            + "            <mtext> </mtext>"
            + "            <mi>b</mi>"
            + "            <mtext>'s</mtext>"
            + "          </mrow>"
            + "        </mover>"
            + "      </mover>"
            + "    </mrow>"
            + "    <munder>"
            + "      <mo>&UnderBrace;</mo>"
            + "      <mrow>"
            + "        <mi>k</mi>"
            + "        <mo>+</mo>"
            + "        <mi>&ell;</mi>"
            + "        <mtext> elements</mtext>"
            + "      </mrow>"
            + "    </munder>"
            + "  </munder>"
            + "  <mo stretchy=\"false\">}</mo>"
            + "</mrow>"
            + "</math>"
            + "</td></tr>"
            + "<tr>"
            + "<td>23</td>"
            + "<td><img src=\"https://developer.mozilla.org/@api/deki/files/4604/=ex53.png\" width=\"213\" height=\"108\" alt=\"TeXbook, 18.42\" /></td>"
            + "<td>"
            + "<math display=\"block\">"
            + "<mrow>"
            + "  <mo>(</mo>"
            + "  <mtable>"
            + "    <mtr>"
            + "      <mtd columnalign=\"center\">"
            + "        <mrow>"
            + "          <mo>(</mo>"
            + "          <mtable>"
            + "            <mtr>"
            + "              <mtd columnalign=\"center\">"
            + "                <mi>a</mi>"
            + "              </mtd>"
            + "              <mtd columnalign=\"center\">"
            + "                <mi>b</mi>"
            + "              </mtd>"
            + "            </mtr>"
            + "            <mtr>"
            + "              <mtd columnalign=\"center\">"
            + "                <mi>c</mi>"
            + "              </mtd>"
            + "              <mtd columnalign=\"center\">"
            + "                <mi>d</mi>"
            + "              </mtd>"
            + "            </mtr>"
            + "          </mtable>"
            + "          <mo>)</mo>"
            + "        </mrow>"
            + "      </mtd>"
            + "      <mtd columnalign=\"center\">"
            + "        <mrow>"
            + "          <mo>(</mo>"
            + "          <mtable>"
            + "            <mtr>"
            + "              <mtd columnalign=\"center\">"
            + "                <mi>e</mi>"
            + "              </mtd>"
            + "              <mtd columnalign=\"center\">"
            + "                <mi>f</mi>"
            + "              </mtd>"
            + "            </mtr>"
            + "            <mtr>"
            + "              <mtd columnalign=\"center\">"
            + "                <mi>g</mi>"
            + "              </mtd>"
            + "              <mtd columnalign=\"center\">"
            + "                <mi>h</mi>"
            + "              </mtd>"
            + "            </mtr>"
            + "          </mtable>"
            + "          <mo>)</mo>"
            + "        </mrow>"
            + "      </mtd>"
            + "    </mtr>"
            + "    <mtr>"
            + "      <mtd columnalign=\"center\">"
            + "        <mn>0</mn>"
            + "      </mtd>"
            + "      <mtd columnalign=\"center\">"
            + "        <mrow>"
            + "          <mo>(</mo>"
            + "          <mtable>"
            + "            <mtr>"
            + "              <mtd columnalign=\"center\">"
            + "                <mi>i</mi>"
            + "              </mtd>"
            + "              <mtd columnalign=\"center\">"
            + "                <mi>j</mi>"
            + "              </mtd>"
            + "            </mtr>"
            + "            <mtr>"
            + "              <mtd columnalign=\"center\">"
            + "                <mi>k</mi>"
            + "              </mtd>"
            + "              <mtd columnalign=\"center\">"
            + "                <mi>l</mi>"
            + "              </mtd>"
            + "            </mtr>"
            + "          </mtable>"
            + "          <mo>)</mo>"
            + "        </mrow>"
            + "      </mtd>"
            + "    </mtr>"
            + "  </mtable>"
            + "  <mo>)</mo>"
            + "</mrow>"
            + "</math>"
            + "</td></tr>"
            + "<tr>"
            + "<td>24</td>"
            + "<td><img src=\"https://developer.mozilla.org/@api/deki/files/4605/=ex54.png\" width=\"344\" height=\"130\" alt=\"TeXbook, 18.43\" /></td>"
            + "<td>"
            + "<math display=\"block\">"
            + "<mrow>"
            + "  <mi>det</mi>"
            + "  <mo>|</mo>"
            + "  <mtable>"
            + "    <mtr>"
            + "      <mtd columnalign=\"center\">"
            + "        <msub>"
            + "          <mi>c</mi>"
            + "          <mn>0</mn>"
            + "        </msub>"
            + "      </mtd>"
            + "      <mtd columnalign=\"center\">"
            + "        <msub>"
            + "          <mi>c</mi>"
            + "          <mn>1</mn>"
            + "        </msub>"
            + "      </mtd>"
            + "      <mtd columnalign=\"center\">"
            + "        <msub>"
            + "          <mi>c</mi>"
            + "          <mn>2</mn>"
            + "        </msub>"
            + "      </mtd>"
            + "      <mtd columnalign=\"center\">"
            + "        <mo>&mldr;</mo>"
            + "      </mtd>"
            + "      <mtd columnalign=\"center\">"
            + "        <msub>"
            + "          <mi>c</mi>"
            + "          <mi>n</mi>"
            + "        </msub>"
            + "      </mtd>"
            + "    </mtr>"
            + "    <mtr>"
            + "      <mtd columnalign=\"center\">"
            + "        <msub>"
            + "          <mi>c</mi>"
            + "          <mn>1</mn>"
            + "        </msub>"
            + "      </mtd>"
            + "      <mtd columnalign=\"center\">"
            + "        <msub>"
            + "          <mi>c</mi>"
            + "          <mn>2</mn>"
            + "        </msub>"
            + "      </mtd>"
            + "      <mtd columnalign=\"center\">"
            + "        <msub>"
            + "          <mi>c</mi>"
            + "          <mn>3</mn>"
            + "        </msub>"
            + "      </mtd>"
            + "      <mtd columnalign=\"center\">"
            + "        <mo>&mldr;</mo>"
            + "      </mtd>"
            + "      <mtd columnalign=\"center\">"
            + "        <msub>"
            + "          <mi>c</mi>"
            + "          <mrow>"
            + "            <mi>n</mi>"
            + "            <mo>+</mo>"
            + "            <mn>1</mn>"
            + "          </mrow>"
            + "        </msub>"
            + "      </mtd>"
            + "    </mtr>"
            + "    <mtr>"
            + "      <mtd columnalign=\"center\">"
            + "        <msub>"
            + "          <mi>c</mi>"
            + "          <mn>2</mn>"
            + "        </msub>"
            + "      </mtd>"
            + "      <mtd columnalign=\"center\">"
            + "        <msub>"
            + "          <mi>c</mi>"
            + "          <mn>3</mn>"
            + "        </msub>"
            + "      </mtd>"
            + "      <mtd columnalign=\"center\">"
            + "        <msub>"
            + "          <mi>c</mi>"
            + "          <mn>4</mn>"
            + "        </msub>"
            + "      </mtd>"
            + "      <mtd columnalign=\"center\">"
            + "        <mo>&mldr;</mo>"
            + "      </mtd>"
            + "      <mtd columnalign=\"center\">"
            + "        <msub>"
            + "          <mi>c</mi>"
            + "          <mrow>"
            + "            <mi>n</mi>"
            + "            <mo>+</mo>"
            + "            <mn>2</mn>"
            + "          </mrow>"
            + "        </msub>"
            + "      </mtd>"
            + "    </mtr>"
            + "    <mtr>"
            + "      <mtd columnalign=\"center\">"
            + "        <mo>&#x22EE;</mo>"
            + "      </mtd>"
            + "      <mtd columnalign=\"center\">"
            + "        <mo>&#x22EE;</mo>"
            + "      </mtd>"
            + "      <mtd columnalign=\"center\">"
            + "        <mo>&#x22EE;</mo>"
            + "      </mtd>"
            + "      <mtd columnalign=\"center\">"
            + "      </mtd>"
            + "      <mtd columnalign=\"center\">"
            + "        <mo>&#x22EE;</mo>"
            + "      </mtd>"
            + "    </mtr>"
            + "    <mtr>"
            + "      <mtd columnalign=\"center\">"
            + "        <msub>"
            + "          <mi>c</mi>"
            + "          <mi>n</mi>"
            + "        </msub>"
            + "      </mtd>"
            + "      <mtd columnalign=\"center\">"
            + "        <msub>"
            + "          <mi>c</mi>"
            + "          <mrow>"
            + "            <mi>n</mi>"
            + "            <mo>+</mo>"
            + "            <mn>1</mn>"
            + "          </mrow>"
            + "        </msub>"
            + "      </mtd>"
            + "      <mtd columnalign=\"center\">"
            + "        <msub>"
            + "          <mi>c</mi>"
            + "          <mrow>"
            + "            <mi>n</mi>"
            + "            <mo>+</mo>"
            + "            <mn>2</mn>"
            + "          </mrow>"
            + "        </msub>"
            + "      </mtd>"
            + "      <mtd columnalign=\"center\">"
            + "        <mo>&mldr;</mo>"
            + "      </mtd>"
            + "      <mtd columnalign=\"center\">"
            + "        <msub>"
            + "          <mi>c</mi>"
            + "          <mrow>"
            + "            <mn>2</mn>"
            + "            <mi>n</mi>"
            + "          </mrow>"
            + "        </msub>"
            + "      </mtd>"
            + "    </mtr>"
            + "  </mtable>"
            + "  <mo>|</mo>"
            + "  <mo>&gt;</mo>"
            + "  <mn>0</mn>"
            + "</mrow>"
            + "</math>"
            + "</td></tr>"
            + "<tr>"
            + "<td>25</td>"
            + "<td><img src=\"https://developer.mozilla.org/@api/deki/files/4598/=ex6.png\" width=\"25\" height=\"14\" alt=\"TeXbook, 16.2-16.3\" /></td>"
            + "<td>"
            + "<math display=\"block\">"
            + "<msub>"
            + "  <mi>y</mi>"
            + "  <msub>"
            + "    <mi>x</mi>"
            + "    <mn>2</mn>"
            + "  </msub>"
            + "</msub>"
            + "</math>"
            + "</td></tr>"
            + "<tr>"
            + "<td>26</td>"
            + "<td><img src=\"https://developer.mozilla.org/@api/deki/files/4583/=ex7.png\" width=\"90\" height=\"23\" alt=\"TeXbook, 16.4-16.5\" /></td>"
            + "<td>"
            + "<math display=\"block\">"
            + "<mrow>"
            + "  <msubsup>"
            + "    <mi>x</mi>"
            + "    <mn>92</mn>"
            + "    <mn>31415</mn>"
            + "  </msubsup>"
            + "  <mo>+</mo>"
            + "  <mi>&pi;</mi>"
            + "</mrow>"
            + "</math>"
            + "</td></tr>"
            + "<tr>"
            + "<td>27</td>"
            + "<td><img src=\"https://developer.mozilla.org/@api/deki/files/4584/=ex8.png\" width=\"27\" height=\"36\" alt=\"TeXbook, 16.4-16.5\" /></td>"
            + "<td>"
            + "<math display=\"block\">"
            + "<msubsup>"
            + "  <mi>x</mi>"
            + "  <msubsup>"
            + "    <mi>y</mi>"
            + "    <mi>b</mi>"
            + "    <mi>a</mi>"
            + "  </msubsup>"
            + "  <msubsup>"
            + "    <mi>z</mi>"
            + "    <mi>c</mi>"
            + "    <mi>d</mi>"
            + "  </msubsup>"
            + "</msubsup>"
            + "</math>"
            + "</td></tr>"
            + "<tr>"
            + "<td>28</td>"
            + "<td><img src=\"https://developer.mozilla.org/@api/deki/files/4585/=ex9.png\" width=\"24\" height=\"22\" alt=\"TeXbook, 16.4-16.5\" /></td>"
            + "<td>"
            + "<math display=\"block\">"
            + "<msubsup>"
            + "  <mi>y</mi>"
            + "  <mn>3</mn>"
            + "  <mrow>"
            + "    <mo>&prime;</mo>"
            + "    <mo>&prime;</mo>"
            + "    <mo>&prime;</mo>"
            + "  </mrow>"
            + "</msubsup>"
            + "</math>"
            + "</td></tr>"
            + "</table>";

    String content = "<!doctype html>"
            + "<html>"
            + "   <head>"
            + "      <meta charset=\"UTF-8\">"
            + "      <title>Petite démonstration de JavaFW et MathML.</title>"
            + "   </head>"
            + "   <body>"
            + "      <p>"
            + "         Ce texte comprenant du code MathML est affiché avec l'éditeur HTML de JavaFX"
            + "      </p>"
            + "      <p>"
            + "         <math>"
            + "            <mrow>"
            + "               <msup><mi>a</mi><mn>2</mn></msup>"
            + "               <mo>+</mo>"
            + "               <msup><mi>b</mi><mn>2</mn></msup>"
            + "               <mo>=</mo>"
            + "               <msup><mi>c</mi><mn>2</mn></msup>"
            + "            </mrow>"
            + "         </math>"
            + "      </p>"
            + "      <p>"
            + "         <math>"
            + "	       <mrow>"
            + "               <mfrac>"
            + "    	            <mrow> <mi>x</mi><mo>+</mo><mn>2</mn></mrow>"
            + "    	            <mrow><mn>3</mn></mrow>"
            + "               </mfrac>"
            + "            </mrow>"
            + "         </math>"
            + "      </p>"
            + "      <p>"
            + "         <math>"
            + "	       <mrow>"
            + "               <mfrac>"
            + "    	            <mn>2</mn>"
            + "    	            <mn>3</mn>"
            + "               </mfrac>"
            + "            </mrow>"
            + "         </math>"
            + "      </p>"
            + "      <p>"
            + "         <math>"
            + "	       <mrow>"
            + "               <mroot>"
            + "    	            <mn>16</mn>"
            + "               </mroot>"
            + "            </mrow>"
            + "         </math>"
            + "      </p>"
            + "      <p>"
            + "         <math>"
            + "            <mrow>"
            + "              <mi>A</mi>"
            + "              <mo>=</mo>"
            + "              <mfenced open=\"[\" close=\"]\">"
            + "                 <mtable>"
            + "                    <mtr>"
            + "                       <mtd><mi>x</mi></mtd>"
            + "                       <mtd><mi>y</mi></mtd>"
            + "                    </mtr>"
            + "                    <mtr>"
            + "                       <mtd><mi>z</mi></mtd>"
            + "                       <mtd><mi>w</mi></mtd>"
            + "                    </mtr>"
            + "                 </mtable>"
            + "              </mfenced>"
            + "            </mrow>"
            + "          </math>"
            + "      </p>"
            + "      <ul>"
            + "         <li>" + javaversion + "</li>"
            + "         <li>" + javafxversion + "</li>"
            + "         <li>" + osinfo + "</li>"
            + "         <li>" + osarch + "</li>"
            + "         <li>" + agent + "</li>"
            + "      </ul>"
            + Content2
            + "   </body>"
            + "</html> ";

}

class myHTMLEditor extends HTMLEditor {

    myHTMLEditor() {
        super();
    }

    @Override
    protected void layoutChildren() {
        super.layoutChildren(); //To change body of generated methods, choose Tools | Templates.
    }

}
